In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('olist_geolocation_dataset.csv')

In [4]:
df.shape

(1000163, 5)

In [5]:
df.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [6]:
df.iloc[13056]

geolocation_zip_code_prefix         1403
geolocation_lat               -23.564542
geolocation_lng               -46.649343
geolocation_city               sao paulo
geolocation_state                     SP
Name: 13056, dtype: object

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  str
 4   geolocation_state            1000163 non-null  str
dtypes: float64(2), int64(1), str(2)
memory usage: 38.2 MB

In [8]:
df['geolocation_zip_code_prefix'] = df['geolocation_zip_code_prefix'].astype(str)

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  str
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  str
 4   geolocation_state            1000163 non-null  str
dtypes: float64(2), str(3)
memory usage: 38.2 MB

In [10]:
df.duplicated()

0          False
1          False
2          False
3          False
4          False
           ...
1000158    False
1000159     True
1000160     True
1000161    False
1000162     True
Length: 1000163, dtype: bool

In [11]:
df[df.duplicated()]

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
15,1046,-23.546081,-46.644820,sao paulo,SP
44,1046,-23.546081,-46.644820,sao paulo,SP
65,1046,-23.546081,-46.644820,sao paulo,SP
66,1009,-23.546935,-46.636588,sao paulo,SP
67,1046,-23.546081,-46.644820,sao paulo,SP
...,...,...,...,...,...
1000153,99970,-28.343273,-51.873734,ciriaco,RS
1000154,99950,-28.070493,-52.011342,tapejara,RS
1000159,99900,-27.877125,-52.224882,getulio vargas,RS
1000160,99950,-28.071855,-52.014716,tapejara,RS
1000162,99950,-28.070104,-52.018658,tapejara,RS

In [12]:
df = df.drop_duplicates()

In [13]:
df.shape

(738332, 5)

In [14]:
df.duplicated()

0          False
1          False
2          False
3          False
4          False
           ...
1000155    False
1000156    False
1000157    False
1000158    False
1000161    False
Length: 738332, dtype: bool

In [15]:
df.duplicated()

0          False
1          False
2          False
3          False
4          False
           ...
1000155    False
1000156    False
1000157    False
1000158    False
1000161    False
Length: 738332, dtype: bool

In [16]:
df[df.duplicated()]

Empty DataFrame
Columns: [geolocation_zip_code_prefix, geolocation_lat, geolocation_lng, geolocation_city, geolocation_state]
Index: []

In [17]:
df.duplicated().sum()

np.int64(0)

In [18]:
df.info()

<class 'pandas.DataFrame'>
Index: 738332 entries, 0 to 1000161
Data columns (total 5 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   geolocation_zip_code_prefix  738332 non-null  str
 1   geolocation_lat              738332 non-null  float64
 2   geolocation_lng              738332 non-null  float64
 3   geolocation_city             738332 non-null  str
 4   geolocation_state            738332 non-null  str
dtypes: float64(2), str(3)
memory usage: 33.8 MB

In [19]:
df.head(1)

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP

In [20]:
df.shape

(738332, 5)

In [21]:
df['geolocation_zip_code_prefix'].nunique()

19015

In [22]:
df.isna().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [23]:
df.to_csv(r'D:\Cart2Insights\Data\Cleaned\clist_geolocation_dataset.csv',index=False)

OSError: Cannot save file into a non-existent directory: 'D:\Cart2Insights\Data\Cleaned'