In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('olist_sellers_dataset.csv')

In [3]:
df.shape

(3095, 4)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   str
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   str
 3   seller_state            3095 non-null   str
dtypes: int64(1), str(3)
memory usage: 96.8 KB

In [5]:
df['seller_zip_code_prefix']=df['seller_zip_code_prefix'].astype(str)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   str
 1   seller_zip_code_prefix  3095 non-null   str
 2   seller_city             3095 non-null   str
 3   seller_state            3095 non-null   str
dtypes: str(4)
memory usage: 96.8 KB

In [7]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
3090    False
3091    False
3092    False
3093    False
3094    False
Length: 3095, dtype: bool

In [8]:
df[df.duplicated()]

Empty DataFrame
Columns: [seller_id, seller_zip_code_prefix, seller_city, seller_state]
Index: []

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   str
 1   seller_zip_code_prefix  3095 non-null   str
 2   seller_city             3095 non-null   str
 3   seller_state            3095 non-null   str
dtypes: str(4)
memory usage: 96.8 KB

In [11]:
df.shape

(3095, 4)

In [12]:
df.head(1)

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP

In [13]:
df['seller_id'].nunique()

3095

In [14]:
df.isnull().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [15]:
df.to_csv(r'D:\Cart2Insights\Data\Cleaned\clist_sellers_dataset.csv',index=False)